### ISSUE TITLE
Allow adding public SSH keys per user

### ISSUE THREAD

**Issue by bertvv** [bertvv/ansible-role-rh-base#19]
The role now allows to add only a single SSH key for a single user. However, there is no reason not to allow adding multiple public keys to each user, e.g.:

```yaml
rhbase_users:
  - name: johndoe
    comment: 'John Doe'
    groups:
      - users
      - devs
    password: '$6$WIFkXf07Kn3kALDp$fHbqRKztuufS895easdT [...]'
    ssh_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7f5e9yzcYxa/JsM6h/tD...'
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChdORbzxsIS+ydsZXVz...'
```
