### ISSUE TITLE
rhbase_user_groups is being treated as a string

### ISSUE THREAD

**Issue by thomasaelbrecht** [bertvv/ansible-role-rh-base#25]
With this config:
```
rhbase_users:
  - name: thomas
    groups:
      - wheel
    password: '...'
    ssh_key: '...'
```

`rhbase_user_groups` is being treated as a string. With the above config it'll have the string value `['wheel']` where a group will be created for every character in that string.

Change this line:
https://github.com/bertvv/ansible-role-rh-base/blob/9486dc90c55fb0de0b02444906d0673eccb24df1/tasks/users.yml#L7

To `rhbase_user_groups: "{{ rhbase_user_groups + item.groups|default([]) }}"`
